name: Action Sample

on:
  repository_dispatch:
    types: [i]
jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - name: Upgrade pip
        run: pip install --upgrade pip        
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run setting
        run: python setting.py
      - name: Run main
        run: python scratch.py